apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${env}
  name: ${cc-name}-deployment
  labels:
    app: ${cc-name}
    env: oda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${cc-name}
      env: oda
  template:
    metadata:
      labels:
        app: ${cc-name}
        env: oda
    spec:
      serviceAccountName: oci-service-account
      imagePullSecrets:
        - name: oci-secret
      containers:
        - name: ${cc-name}
          imagePullPolicy: Always
          image: ${ocir_registry_url}/${ocir_namespace}/${cc-name}:v1
          ports:
            - containerPort: 3000
              name: ${cc-name}-port
---
apiVersion: v1
kind: Service
metadata:
  name: ${cc-name}-svc
  namespace: ${env}
spec:
  selector:
    app: ${cc-name}
    env: oda
  ports:
    - name: svc-${cc-name}-port
      protocol: TCP
      port: 80
      targetPort: ${cc-name}-port
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${cc-name}-ingress
  namespace: ${env}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: "nginx"
  rules:
    - http:
        paths:
          - path: /${cc-name}/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ${cc-name}-svc
                port:
                  name: svc-${cc-name}-port
